apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-boot-api
  template:
    metadata:
      labels:
        app: spring-boot-api
    spec:
      containers:
        - name: spring-boot-api
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          command: ["sh", "-c", "sleep infinity"]
          volumeMounts:
          - name: config
            mountPath: "/app/config"
            readOnly: true
    volumes:
    - name: config
      configMap:
        name: spring-boot-api-config