apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-boot-api
  template:
    metadata:
      labels:
        app: spring-boot-api
    spec:
      containers:
        - name: spring-boot-api
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          command: ["sh", "-c", "sleep infinity"]